name: image_to_text_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+2
  google_mlkit_text_recognition:
  permission_handler: ^10.4.3
  image: ^4.2.0
  google_ml_kit: ^0.18.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  glassmorphism: ^3.0.0
  glass_kit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
